### ISSUE TITLE
Is the channel in WHO reply always arbitrary?

### ISSUE THREAD

**Issue by emersion** [ircdocs/modern-irc#209]
The channel returned in `RPL_WHOREPLY` is arbitrary when the mask passed to `WHO` is not a channel, as documented in modern-irc:

> `<channel>` is an arbitrary channel the client is joined to

But is this the case when the client sends `WHO #chan`? In that case, is the `RPL_WHOREPLY` guaranteed to return replies with `#chan`?

Hexchat seems to assume this.

**Comment by classabbyamp** [comment]
the way I read [hexchat's handling of RPL_WHOSPCRPL](https://github.com/hexchat/hexchat/blob/master/src/common/proto-irc.c#L750-L776), it assumes a `WHO` that replies with a channel of `*` is user-initiated because it can't associate the response with an internally-initiated `WHO` (which is decided by matching the channel and server to a list of `WHO`s it has sent)

**Comment by progval** [comment]
You can add a new test to irctest based on this one: https://github.com/progval/irctest/blob/136a7923c09d3cea3ab13f5dfe042d011a5b9615/irctest/server_tests/who.py#L300 but joining two channels and using `WHO` on both.

If you send a PR, the CI will automatically test it on all the servers present here: https://dashboard.irctest.limnoria.net/irctest.server_tests.who.xhtml

**Comment by progval** [comment]
yup
