### ISSUE TITLE
What about the two features?

### ISSUE THREAD

**Issue by yarcowang** [ircdocs/modern-irc#31]
I like IRC. But I'm not sure I understand the low-level thing, so here are my two assumptions:

1. It can support web socket? (server end?)
2. It can filter content in a channel, ex.: I can set myself to a mode when in a channel, where I only accept receiving those messages @ me, or for some keywords show up. (maybe client end)

**Comment by DanielOaks** [comment]
Hey, sure. With regards to websockets, both [Charybdis](https://github.com/charybdis-ircd/charybdis/) and [InspIRCd](https://github.com/inspircd/inspircd) have websocket implementations, although there's no standard API written up for them at this point so I haven't approached that.

For that sort of filtering, you'd likely be doing it client-side. Some IRC servers may have modes that let you restrict specific types of content in channels – say block set bad words or similar – but not like you're describing.

**Comment by yarcowang** [comment]
I'm thinking the messages in IRC channel should be classified, for example, when I'm at office or in spare time, I'd like to switch between different modes: when at office, maybe I'd like to accept some important messages contains some words or some guys I understand very well; but when in spare time, I can also quickly to switch to the full mode to see what's happening.

And maybe also the webhook (like hipchat/slack can integrate with Github, of cause there's the Robot solution, but I feel it is not the right way)...

Also json messages and rich text format?

**Comment by DanielOaks** [comment]
Definitely, lots of stuff that'd be cool to have. However, the documents here aim to describe existing features and implementations rather than new stuff.

I think it'd be good to look towards [IRCv3](http://ircv3.net/), since they handle new features and protocol extensions. To go through your suggestions through:

JSON message transport has been looked at and is planned, can see more details about it here: https://github.com/ircv3/ircv3-specifications/issues/57

For rich text formats, some people have put forth things like markdown message formatting with c2c tags (which will likely be approached further as c2c tags get finished, and then adopted by servers). For stuff that works now though, feel free to take a look at my formatting doc here: http://modern.ircdocs.horse/formatting.html

**Comment by DanielOaks** [comment]
I'll close this for now. However, as mentioned, working with IRCv3 and server/client devs is probably your best bet if you wanna push this stuff forwards!
