### ISSUE TITLE
Can we get rid of legacy formatting entirely?

### ISSUE THREAD

**Issue by SoniEx2** [ircdocs/modern-irc#52]
We're running out of control codes. To avoid running out of control codes, let's come up with an extensible formatting scheme that doesn't run out of control codes.

I propose something like ANSI escape codes, but designed with IRC in mind. That way, we have infinite control codes and infinite formatting styles and it's trivial to add new ones.

Marquee, blink, etc could be added without conflicting with existing control codes. In addition to that, some codes are currently used for encryption and such, so they'd conflict too.

**Comment by DanielOaks** [comment]
Nah, sorry man. I don't think it's correct to call it _legacy_ when the support out there for some of it is over 50 or at 100%.

Keep in mind, Modern isn't a project to specify new stuff, just to have accurate specifications of the IRC protocol as it is used today. So I have no place specifying this entirely new system.

**Comment by SoniEx2** [comment]
so why not rename it "the-irc-descriptivist" or some other similarly catchy, more accurate title?

**Comment by DanielOaks** [comment]
I think it's plenty accurate as-is. They're modern IRC specifications, rather than most of the ones people currently refer to which are over 20 years old (1459), or at least a good 10 years old at this point.

**Comment by SoniEx2** [comment]
they're still mostly legacy, just like ANSI control codes and the original CTCP are legacy. they're *old*, even if they're still in use they're not modern.

C89 is legacy. many modern projects are strictly C89, but that doesn't make C89 modern.

(I could insert more examples, but I think you get the idea)

**Comment by DanielOaks** [comment]
Okay. They're modern specifications describing how the protocol works today. That's why I've named this set of specifications the Modern specs. I don't claim that the protocol or features I'm describing themselves are modern, and the name somewhat plays off the fact that IRC itself is a very old protocol, so I'm all good leaving it as-is thanks.

**Comment by DanielOaks** [comment]
To follow on from this, I'm documenting DCC (the unencrypted nature of DCC is something I very much dislike). DCC is terrible and we really should have a better system by now, but we don't. However, we do have DCC, which is why I'm documenting it (and hopefully, from this document we're able to see exactly what does exist out there, and build a better system or build improvements on top of what already exists). Same thing for the CTCP I-D, we documented a subset of functionality that's currently in-use by most clients.

For this to exist, you would need to do the leg work of writing up a specification that implements it, somehow work in compatibility or a way to keep this 'legacy' formatting working, and then go around to the different IRC clients out there and actually get it implemented in running code. If you're able to do so, I'll gladly document it here!

**Comment by SoniEx2** [comment]
What's I-D in CTCP I-D?

**Comment by DanielOaks** [comment]
CTCP Internet-Draft submitted to the IETF: https://tools.ietf.org/html/draft-oakley-irc-ctcp-01
